spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce 
spring.jpa.hibernate.ddl-auto=update spring.jpa.show-sql=true 

spring.datasource.username=postgres
spring.datasource.password=hi2005ba
spring.jpa.hibernate.ddl-auto=update
