server.port=8761
spring.application.name=eureka-server

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# Desactiver les logs verbeux d'Eureka
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
